import { z } from "zod";
import { getStripe, CURRENCY } from "@/lib/stripe/client";
import { createAdminClient } from "@/lib/supabase/admin";
import { priceCart } from "@/lib/cart/pricing";
import { cartLinesSchema } from "@/lib/cart/parse";
import { orderItemRows } from "@/lib/cart/order-items";
import { checkoutAttemptKey, IDEMPOTENCY_KEY_PATTERN } from "@/lib/cart/attempt-key";
import { allowByIp, RATE_LIMITS } from "@/lib/rate-limit";
import { PG_UNIQUE_VIOLATION } from "@/lib/supabase/errors";

export const runtime = "nodejs";

/**
 * Creates the order and its PaymentIntent.
 *
 * THE AMOUNT CHARGED IS COMPUTED HERE, from database prices. The request body
 * carries product ids, sizes and quantities — never a price, never a total. If
 * it did, anyone could buy a $3,400 gown for $1 by editing one number.
 *
 * The order is written as `pending_payment`; only the Stripe webhook promotes it
 * to `paid`. The browser is never trusted to confirm its own payment.
 *
 * DOUBLE SUBMIT
 * -------------
 * Every caller must send an `Idempotency-Key` header, minted once per checkout
 * attempt. Previously the only thing standing between a double-tap and two
 * orders was `disabled={busy}` on a button: the Stripe idempotency key was
 * derived from `order.id`, which is generated by the insert, so two requests
 * produced two orders, two keys and two PaymentIntents. A native client gets no
 * disabled button for free, so that protection did not survive contact with a
 * second client.
 *
 * The order of operations is now Stripe first:
 *
 *   1. Create the PaymentIntent keyed on the caller's attempt id. A repeat
 *      request returns Stripe's *existing* intent rather than a new one.
 *   2. Look for an order already carrying that intent id. Found means this
 *      attempt has been served before — return it unchanged.
 *   3. Otherwise insert, with the intent id set in the same statement, so the
 *      existing unique constraint on `stripe_payment_intent_id` makes a
 *      concurrent duplicate lose the race rather than create a second order.
 *
 * The intent briefly exists without `metadata.order_id`, which the webhook
 * needs. That window is safe because it closes before the client secret is
 * returned — nobody can confirm a payment they have no secret for. If the
 * process dies inside the window, the next attempt with the same key finds the
 * orphaned intent and adopts it.
 */

const bodySchema = z.object({
  // Shared with the cart server action rather than duplicated. Ids stay plain
  // strings here — nothing about a uuid in a request body proves it belongs to
  // a ready-to-wear piece, so the branded type is minted inside priceCart,
  // after Postgres has filtered on kind.
  lines: cartLinesSchema.min(1),
  customer: z.object({
    email: z.string().email(),
    firstName: z.string().min(1).max(100),
    lastName: z.string().min(1).max(100),
    phone: z.string().max(40).optional(),
    addressLine1: z.string().min(1).max(200),
    addressLine2: z.string().max(200).optional(),
    suburb: z.string().min(1).max(100),
    state: z.string().min(1).max(50),
    postcode: z.string().min(3).max(10),
    marketingOptIn: z.boolean().default(false),
  }),
});

export async function POST(req: Request): Promise<Response> {
  if (!(await allowByIp("checkout", RATE_LIMITS.checkoutIp))) {
    return Response.json(
      { error: "Too many attempts. Please wait a moment and try again." },
      { status: 429 }
    );
  }

  const clientKey = req.headers.get("idempotency-key");

  if (!clientKey || !IDEMPOTENCY_KEY_PATTERN.test(clientKey)) {
    return Response.json(
      { error: "Missing or malformed Idempotency-Key header" },
      { status: 400 }
    );
  }

  const parsed = bodySchema.safeParse(await req.json().catch(() => null));

  if (!parsed.success) {
    return Response.json({ error: "Invalid request" }, { status: 400 });
  }

  const { lines, customer } = parsed.data;

  // Authoritative pricing. Bespoke ids yield nothing here — priceCart filters
  // to cart-eligible kinds — so a forged payload cannot smuggle a commission in.
  const priced = await priceCart(lines);

  // STOP if anything dropped out.
  //
  // priceCart reports unavailable lines rather than discarding them precisely
  // so the customer can be told. This route used to check only whether the cart
  // had emptied ENTIRELY, so a three-item bag whose middle gown was archived
  // mid-checkout went through as a two-item order at a lower total, with the
  // third silently absent from the confirmation. Charging someone for a
  // different order than the one they reviewed is not recoverable by an apology.
  if (priced.unavailable.length > 0) {
    const everythingWent = priced.lines.length === 0;

    return Response.json(
      {
        error: everythingWent
          ? "Those pieces are no longer available."
          : "Something in your bag is no longer available.",
        unavailableLineIds: priced.unavailable,
      },
      { status: 409 }
    );
  }

  if (priced.lines.length === 0) {
    return Response.json({ error: "No purchasable items in cart" }, { status: 400 });
  }

  const supabase = createAdminClient();

  // The native app tags its requests so its PaymentIntent can exclude redirect
  // methods (see the automatic_payment_methods note below). The browser sends no
  // such header and keeps the full set.
  const isApp = req.headers.get("x-mft-client") === "app";

  // Stripe first. A repeat of this attempt returns the same intent, which is
  // what lets the order lookup below recognise a duplicate.
  let intent;
  try {
    intent = await getStripe().paymentIntents.create(
      {
        amount: priced.totalCents,
        currency: CURRENCY,
        // Which methods Stripe surfaces depends on the caller. In the browser
        // the full set is safe — card, Afterpay, Zip, Apple Pay, Google Pay,
        // Link — because a redirect method returns to the site. The native app
        // cannot yet complete a redirect: its msfairytale:// return URL is
        // unregistered on both platforms, so Afterpay/Zip/PayPal would strand
        // the customer. `allow_redirects: "never"` restricts it to methods that
        // finish in-app until that native return handling is built.
        automatic_payment_methods: isApp
          ? { enabled: true, allow_redirects: "never" }
          : { enabled: true },
        receipt_email: customer.email,
        metadata: { purpose: "order" },
      },
      { idempotencyKey: checkoutAttemptKey(clientKey, priced.totalCents, lines) }
    );
  } catch (err) {
    console.error("[checkout] PaymentIntent create failed:", (err as Error).message);
    return Response.json(
      { error: "We couldn't reach our payment provider. Please try again." },
      { status: 502 }
    );
  }

  // Served this attempt already? Return the same order rather than a second one.
  const { data: seen } = await supabase
    .from("orders")
    .select("order_number, confirmation_token, total_cents, status")
    .eq("stripe_payment_intent_id", intent.id)
    .maybeSingle();

  if (seen) {
    // A cancelled order means the first attempt was abandoned after the intent
    // existed. Reusing it would resurrect a dead order against a spent key, so
    // the caller is told to start again with a fresh one.
    if (seen.status === "cancelled") {
      return Response.json(
        { error: "That checkout attempt expired. Please try again." },
        { status: 409 }
      );
    }

    return Response.json({
      clientSecret: intent.client_secret,
      orderNumber: seen.order_number,
      confirmationToken: seen.confirmation_token,
      totalCents: seen.total_cents,
    });
  }

  const { data: order, error: orderError } = await supabase
    .from("orders")
    .insert({
      email: customer.email,
      first_name: customer.firstName,
      last_name: customer.lastName,
      phone: customer.phone ?? null,
      ship_address_line1: customer.addressLine1,
      ship_address_line2: customer.addressLine2 ?? null,
      ship_suburb: customer.suburb,
      ship_state: customer.state,
      ship_postcode: customer.postcode,
      shipping_method: "express",
      subtotal_cents: priced.subtotalCents,
      shipping_cents: priced.shippingCents,
      total_cents: priced.totalCents,
      gst_cents: priced.gstCents,
      marketing_opt_in: customer.marketingOptIn,
      // Set in the same statement as the insert. The unique constraint on this
      // column is what resolves a genuine race: two concurrent requests that
      // both missed the lookup above cannot both land.
      stripe_payment_intent_id: intent.id,
    })
    .select("id, order_number, confirmation_token")
    .single();

  if (orderError || !order) {
    // A unique violation means a concurrent request won. That is a duplicate,
    // not a failure — read back what it created and serve the same answer.
    if (orderError?.code === PG_UNIQUE_VIOLATION) {
      const { data: raced } = await supabase
        .from("orders")
        .select("order_number, confirmation_token, total_cents")
        .eq("stripe_payment_intent_id", intent.id)
        .maybeSingle();

      if (raced) {
        return Response.json({
          clientSecret: intent.client_secret,
          orderNumber: raced.order_number,
          confirmationToken: raced.confirmation_token,
          totalCents: raced.total_cents,
        });
      }
    }

    console.error("[checkout] order insert failed:", orderError?.message);
    return Response.json({ error: "Could not create order" }, { status: 500 });
  }

  /**
   * Abandons a half-built order.
   *
   * Marks it cancelled rather than deleting it. An UPDATE is far more likely to
   * succeed than a cascading DELETE, it cannot partially fail, and it leaves a
   * record of what was attempted — a row that vanishes tells you nothing when
   * a customer calls about a charge they think they made.
   */
  const abandon = async (reason: string) => {
    const { error } = await supabase
      .from("orders")
      .update({ status: "cancelled" })
      .eq("id", order.id);

    if (error) {
      console.error(`[checkout] could not cancel order ${order.order_number}:`, error.message);
    }
    console.error(`[checkout] abandoned order ${order.order_number}: ${reason}`);
  };

  // Snapshot each line so the order stays a faithful record even if a product is
  // later renamed, repriced or archived. The composite FK here is what makes a
  // bespoke gown physically unable to appear in an order.
  //
  // Built by `orderItemRows` rather than inline: the kind written here must be
  // each line's own. This mapping used to hardcode 'rtw', which made every
  // accessory fail the composite FK. See lib/cart/order-items.ts.
  const { error: itemsError } = await supabase
    .from("order_items")
    .insert(orderItemRows(order.id, priced.lines));

  if (itemsError) {
    await abandon(`order_items insert failed: ${itemsError.message}`);
    return Response.json({ error: "Could not create order" }, { status: 500 });
  }

  // The webhook routes on metadata.order_id, so the intent has to learn which
  // order it belongs to before the client secret goes out. Until this lands the
  // intent is unreconcilable, which is why it happens before the response and
  // not after.
  //
  // A failure here is fatal to the attempt: allowing the customer to pay against
  // an intent the webhook cannot match would take money for an order that never
  // gets marked paid, and no amount of retrying at that point recovers it.
  try {
    await getStripe().paymentIntents.update(intent.id, {
      metadata: {
        purpose: "order",
        order_id: order.id,
        order_number: order.order_number,
      },
    });
  } catch (err) {
    await abandon(`PaymentIntent metadata update failed: ${(err as Error).message}`);
    return Response.json(
      { error: "We couldn't reach our payment provider. Please try again." },
      { status: 502 }
    );
  }

  return Response.json({
    clientSecret: intent.client_secret,
    orderNumber: order.order_number,
    confirmationToken: order.confirmation_token,
    totalCents: priced.totalCents,
  });
}
