import { createHash } from "node:crypto";

/**
 * Identifies one checkout attempt, for Stripe's idempotency key.
 *
 * The caller supplies an opaque attempt id (minted once per checkout, sent as
 * the `Idempotency-Key` header). This folds the priced cart into it.
 *
 * Both halves are load-bearing:
 *
 *   The caller's id is what makes a double-tap idempotent. Without it every
 *   request is a fresh attempt, which is the bug this replaced — the old key
 *   was derived from `order.id`, generated by the insert, so two submits
 *   produced two orders and two PaymentIntents.
 *
 *   The cart fingerprint is what stops a *stale* id from being wrong. Stripe
 *   rejects a reused key whose parameters differ, so a customer who edits their
 *   bag and resubmits without remounting would otherwise get an opaque 400.
 *   Folding the cart in makes an edited bag a genuinely new attempt, which is
 *   what it is.
 *
 * Lines are sorted, so reordering the same bag is the same attempt — cart order
 * is a UI detail and must not mint a second order.
 */
export function checkoutAttemptKey(
  clientKey: string,
  totalCents: number,
  lines: readonly { productId: string; size: string; qty: number }[]
): string {
  const fingerprint = createHash("sha256")
    .update(
      lines
        .map((l) => `${l.productId}:${l.size}:${l.qty}`)
        .sort()
        .join("|") + `|${totalCents}`
    )
    .digest("hex")
    .slice(0, 16);

  return `checkout_${clientKey}_${fingerprint}`;
}

/**
 * Opaque to the server — only length and alphabet are constrained, so any
 * client can use a uuid, a ulid, or its own scheme.
 */
export const IDEMPOTENCY_KEY_PATTERN = /^[A-Za-z0-9_-]{16,200}$/;
